apiVersion: apps/v1
kind: Deployment
metadata:
  name: qualidoc-backend
  namespace: qualidoc
  labels:
    app: qualidoc-backend
    version: "1.0.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: qualidoc-backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0        # zéro downtime
  template:
    metadata:
      labels:
        app: qualidoc-backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: backend
          image: localhost:5000/qualidoc-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: qualidoc-config
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: qualidoc-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: qualidoc-secrets
                  key: DB_PASSWORD
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: qualidoc-secrets
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: qualidoc-secrets
                  key: MINIO_SECRET_KEY
            - name: MAIL_USER
              valueFrom:
                secretKeyRef:
                  name: qualidoc-secrets
                  key: MAIL_USER
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: qualidoc-secrets
                  key: MAIL_PASSWORD
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: qualidoc
spec:
  selector:
    app: qualidoc-backend
  ports:
    - port: 8080
      targetPort: 8080
