apiVersion: v1
kind: ConfigMap
metadata:
  name: qualidoc-config
  namespace: qualidoc
data:
  # Backend
  DB_URL: "jdbc:postgresql://postgres-service:5432/qualidoc"
  JWT_ACCESS_EXPIRATION: "900"
  JWT_REFRESH_EXPIRATION: "604800"

  MINIO_ENDPOINT: "http://minio-service:9000"
  MINIO_BUCKET: "qualidoc-documents"
  ELASTICSEARCH_URI: "http://elasticsearch-service:9200"
  MAIL_HOST: "smtp.qualidoc.fr"
  MAIL_PORT: "587"

  # Elasticsearch
  discovery.type: "single-node"
  xpack.security.enabled: "false"
  ES_JAVA_OPTS: "-Xms512m -Xmx512m"
